Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
def hello():
    print("Hello")

    
def main():
...     hello()
... 
...     
>>> if __name__ == "__main__":
...     main()
... 
...     
Hello
>>> 
>>> if __name__ == "__main__":
...     main()
... 
...     
Hello

>>> if __name__ == "__main__":
...     main()
... 
...     
Hello
>>> if __name__ == "__main__":
...     main()
... 
...     
Hello
>>> if __name__ == "__main__":
...     main()
... 
...     
Hello
if __name__ == "__main__":
...     main()
>>> 
>>> 
>>> if __name__ == "__main__":
...     main()
... 
...     
Hello
